* Experience
** Pixel Toys
August 2017 until present

** Viewpoint Games
June 2016 until present

Senior Programmer on several projects, and prototypes. Design,
architect and implement game from conception to release, including AI,
gameplay and optimisation for VR titles, both for mobile VR and for
consoles.

+ Hungry Shark VR (C#/Unity3D)
+ Ghosts in the Toybox (C#/Unity3D)

 
** FreeStyleGames
May 2013 until May 2016

Software engineer on several projects, providing user interface, gameplay and systems
architecture.

+ Guitar Hero Live (C++)
+ Guitar Hero Live Companion App (C#/Unity3D)
+ Call of Duty: Online (Actionscript)
+ Call of Duty: Ghosts Companion App (C#/Unity3D)

Also worked on a small R&D team exploring different project ideas using a variety of
technologies, such as Virtual Reality, absolute positional controllers, and motion detecting
cameras. 
** AppToyz
January 2013 until May 2013

Lead software engineer on four iOS and Android projects. Developing with Unity3D and
Cocos2D-X.
Primary programming languages: C# and C++
** Ideaworks Game Studio
May 2010 until January 2013

Software engineer on major iOS titles, providing User Interface programming as well as
gameplay, graphics and system architecture. Have worked closely with designers and artists
to create usable workflows when creating the games.

+ Lara Croft and the Guardian of Light (C++) http://nistur.com/pg-cv01
+ Backbreaker 2: Vengeance (C++) http://nistur.com/pg-cv02
+ Transformers 3: Dark of the Moon (C++) http://nistur.com/pg-cv03
+ Call of Duty Black Ops: Zombies (C++) http://nistur.com/pg-cv04
+ Wipeout (C#/Unity3D) http://nistur.com/pg-cv05
