OBJCFLAGS=`gnustep-config --objc-flags --objc-libs` -lobjc -lgnustep-base

FILES=src/render/main.m	  	\
	src/render/row.m	\
	src/render/char.m	\
	src/render/glyph.m	\
	src/render/glyphtable.m	\
	src/render/renderer.m	\
	src/render/framebuffer.m

OUTPUT=out/bin/render

.PHONY: clean dir

$(OUTPUT): dir
	gcc -o $(OUTPUT) $(FILES) $(OBJCFLAGS)


dir:
	mkdir -v -p out/bin

clean:
	@rm -rf $(OUTPUT)