OUT_DIR=bin/

OUTPUT=$(OUT_DIR)/asm8080

OBJS=obj/asm_dir.o \
	obj/exp_parser.o \
	obj/msg.o \
	obj/opcode.o \
	obj/util.o \
	obj/main.o

INC_DIRS=-Iasm8080/src

CFLAGS=$(INC_DIRS) -D_TGT_OS_LINUX32
LDFLAGS=

.PHONY: all clean

all: $(OUTPUT)

$(OUTPUT): $(OBJS)
	g++ -o $@ $(OBJS) $(LDFLAGS)

obj/%.o: asm8080/src/%.c
	gcc -o $@ $< -c $(CFLAGS)

clean:
	@rm -f $(OUTPUT)
	@rm -f $(OBJS) 